apiVersion: v1
kind: Service
metadata:
  name: localrag-api
  namespace: default
  labels:
    app: localrag-api
spec:
  type: ClusterIP
  selector:
    app: localrag-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
